# Generated by Django 3.1.7 on 2021-03-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(blank=True, max_length=20, null=True)),
                ('student_age', models.IntegerField(blank=True, null=True)),
                ('student_address', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
